name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'src/Makefile.am'
      - 'Makefile.am'
      - 'configure.ac'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'src/Makefile.am'
      - 'Makefile.am'
      - 'configure.ac'
      - '.github/workflows/build.yml'
  
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref to build (branch, tag, or commit SHA).'
        required: false
        default: 'main'

jobs:
  on-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.event.inputs.ref || github.ref }}

    - name: Update software sources
      run: sudo apt-get update

    - name: Install GNU Autotools
      run: sudo apt-get install -y autoconf automake libtool
    
    - name: Generate configure script
      run: autoreconf -i
    
    - name: Run configure script
      run: ./configure
    
    - name: Make
      run: make
    
    - name: Run tests
      run: make check

  on-windows-with-mingw:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: set up mingw
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        install: |
          base-devel
          autoconf
          automake
          libtool
      
    - name: Generate configure script
      shell: msys2 {0}
      env:
        CHERE_INVOKING: 1         # Do not run in $HOME
        MSYS2_PATH_TYPE: inherit  # Inherit environment variables
      run: autoreconf -i
    
    - name: Run configure script
      shell: msys2 {0}
      env:
        CHERE_INVOKING: 1
        MSYS2_PATH_TYPE: inherit
      run: ./configure
    
    - name: Make
      shell: msys2 {0}
      env:
        CHERE_INVOKING: 1
        MSYS2_PATH_TYPE: inherit
      run: make
    
    - name: Run tests
      shell: msys2 {0}
      env:
        CHERE_INVOKING: 1
        MSYS2_PATH_TYPE: inherit
      run: make check
