name: Package

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git reference to build (branch, tag, or commit SHA)'
        required: false
        default: 'main'

jobs:
  debian:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.event.inputs.ref || github.ref }}

    - name: Update software sources
      run: sudo apt-get update
    
    - name: Install Packaging Tools
      run: sudo apt-get install -y debhelper devscripts fakeroot build-essential
    
    - name: Prepare Source Directory and Tarball
      run: |
        version=$(dpkg-parsechangelog -S Version | cut -d- -f1)
        source_dir="cp-${version}"
        tarball="cp_${version}.orig.tar.gz"
        rm -rf .git
        cd ..
        cp -rf cp "$source_dir"
        tar -czf "$tarball" "$source_dir"
    
    - name: Debian Package Build
      run: |
        version=$(dpkg-parsechangelog -S Version | cut -d- -f1)
        cd "../cp-${version}"
        debuild -uc -us

    - name: Copy Packages to Current Work Directory
      run: |
        cp ../*.deb ./
        cp ../*.dsc ./
    
    - name: Upload Debian Packages
      uses: actions/upload-artifact@v4
      with:
        name: debian-packages
        path: |
          *.deb
          *.dsc
